name: burnotes-dev

networks:
  infra:
    external: true
    name: burnotes-infra

services:
  app:
    image: ${WERF_APP_DOCKER_IMAGE_NAME:-burnotes:latest}
    command: ["tail", "-f", "/dev/null"]
    # command: ["npm", "run", "dev"]
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
      - app_next_cache:/app/.next
    env_file: .env
    expose:
      - "${APP_PORT}"
    labels:
      - traefik.enable=true
      # - traefik.docker.network=web
      - traefik.http.routers.burnotes.rule=Host(`${APP_HOST}`)
      - traefik.http.routers.burnotes.entrypoints=http
      - traefik.http.services.burnotes.loadbalancer.server.port=${APP_PORT}
      # - traefik.http.routers.burnotes.entrypoints=web
      # - traefik.http.services.burnotes.loadbalancer.server.port=${APP_PORT}
    networks:
      - infra
    restart: unless-stopped

volumes:
  app_node_modules:
  app_next_cache:
